# Full credit goes to https://github.com/conda/conda-recipes for providing this recipe.
# It has been subsequently adapted for automated building with conda-forge.

package:
  name: matplotlib
  version: 1.5.1

source:
  fn: matplotlib-1.5.1.tar.gz
  url: https://github.com/matplotlib/matplotlib/archive/v1.5.1.tar.gz
  sha256: 64c9f7cce4075d05c2602108ee1795aa6455c2c1d8e4329c95c83465e3806887

  patches:
    # A patch to add Tcl directly to the search path on Windows.
    - setupext.patch  # [win]
    # A patch to make Qt4Agg the default backend.
    - cfg_qt4agg.patch  # [linux]
    # Patches the matplotlibrc template to default to Qt4.
    - rctmp_pyside.patch  # [not osx]
    # Patches setupext to look in PREFIX for the tcl/tk headers.
    - osx-tk.patch  # [osx]

build:
    number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - python-dateutil
    - freetype 2.5.*
    - msinttypes  # [win]
    - cycler
    - nose
    - pyparsing
    - pytz
#    - py2cairo  # [linux and py2k]
    - tornado
    - libpng 1.6*
    - zlib 1.2*  # [win]
    - pyqt  # [not osx]
    - tk  # [linux]
  run:
    - python
    - numpy x.x
    - cycler
    - python-dateutil
    - freetype 2.5.*
    - pytz
    - pyparsing
#    - py2cairo  # [linux and py2k]
    - libpng 1.6*
    - pyqt  # [not osx]
    - tk  # [linux]

test:
    imports:
        - matplotlib
        - matplotlib.pyplot

about:
  home: http://matplotlib.org/
  license: PSF-based (http://matplotlib.org/users/license.html)
  summary: Publication quality figures in Python

extra:
  recipe-maintainers:
    - pelson
    - tacaswell
    - janschulz
