# Full credit goes to https://github.com/conda/conda-recipes for providing this recipe.
# It has been subsequently adapted for automated building with conda-forge.

{% set version = "1.5.2" %}

package:
  name: matplotlib
  version: {{ version }}

source:
  fn: matplotlib-{{ version }}.tar.gz
  url: https://github.com/matplotlib/matplotlib/archive/v{{ version }}.tar.gz
  sha256: 14c542780bf44db68b219e2e45c5a8de2c1fe308eea7f78c244b9b9d3923e09b

  patches:
    # Find Tcl and libpng on Windows.
    - setupext.patch  # [win]
    # A patch to make Qt4Agg the default backend.
    - cfg_qt4agg.patch  # [linux]
    # Patches the matplotlibrc template to default to Qt4.
    - rctmp_pyside.patch  # [not osx]

build:
    number: 3  # [not linux]
    number: 4  # [linux]

requirements:
  build:
    - python
    - setuptools
    - pkg-config  # [not win]
    - numpy x.x
    - python-dateutil
    - freetype 2.6.*
    - msinttypes  # [win]
    - cycler
    - nose
    - pyparsing
    - pytz
#    - py2cairo  # [linux and py2k]
    - tornado
    - libpng >=1.6.21,<1.7
    - zlib 1.2.*  # [win]
    - pyqt  # [not osx]
    - tk 8.5.*  # [linux]
  run:
    - python
    - numpy x.x
    - cycler
    - python-dateutil
    - freetype 2.6.*
    - pytz
    - pyparsing
#    - py2cairo  # [linux and py2k]
    - libpng >=1.6.21,<1.7
    - pyqt  # [not osx]
    - tk 8.5.*  # [linux]
    - functools32  # [py2k]

test:
    imports:
        - matplotlib
        - matplotlib.pyplot

about:
  home: http://matplotlib.org/
  license: PSF-based (http://matplotlib.org/users/license.html)
  summary: Publication quality figures in Python

extra:
  recipe-maintainers:
    - mdboom
    - ocefpaf
    - pelson
    - tacaswell
